/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Models.Employee;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.JFrame;


/**
 *
 * @author ThanhNhan
 */
public class Form_Home extends javax.swing.JFrame {
    private final java.awt.Color selectedColor = new java.awt.Color(0, 153, 0);
    private final java.awt.Color defaultColor = new java.awt.Color(204, 255, 204); 
    
    private Employee currentEmployee;
    /**
     * Creates new form Form_Home
     */
    public Form_Home(Employee emp) {
        this.currentEmployee = emp;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        lblAdminName.setText("Xin chào, " + currentEmployee.getEmployeeName() + "!");
        resetPanelBackgrounds();
        panelNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelNhanVien.setBackground(selectedColor);
             
                loadPanel(new Form_Employee()); 
            }
        });

        panelKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelKhachHang.setBackground(selectedColor);

                loadPanel(new Form_Customer());
            }
        });

        panelThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelThucDon.setBackground(selectedColor);

                loadPanel(new Form_Product());
            }
        });
        
        panelHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelHoaDon.setBackground(selectedColor);

                loadPanel(new Form_Invoice());
            }
        });

        panelReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelReport.setBackground(selectedColor);

                loadPanel(new Form_Report());
            }
        });
        
        panelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPanelBackgrounds();
                panelHoaDon.setBackground(selectedColor);
                System.exit(0);
            }
        });
    }

    private void loadPanel(javax.swing.JPanel panel) {
        panelMainContent.removeAll();
        panelMainContent.setLayout(new java.awt.BorderLayout());
        panelMainContent.add(panel, java.awt.BorderLayout.CENTER);
        panelMainContent.revalidate();
        panelMainContent.repaint();
    }
    
    private void resetPanelBackgrounds() {
        panelNhanVien.setBackground(defaultColor);
        panelKhachHang.setBackground(defaultColor);
        panelThucDon.setBackground(defaultColor);
        panelHoaDon.setBackground(defaultColor);
        panelReport.setBackground(defaultColor);
        panelDangXuat.setBackground(defaultColor);
        panelPhieuXuat.setBackground(defaultColor);
        panelPhieuXuat1.setBackground(defaultColor);
        panelPhieuXuat2.setBackground(defaultColor);
    }      
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        panelNhanVien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelKhachHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelThucDon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelHoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelPhieuXuat2 = new javax.swing.JPanel();
        panelPhieuXuat1 = new javax.swing.JPanel();
        panelPhieuXuat = new javax.swing.JPanel();
        panelDangXuat = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelMainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý bán hàng Cộng Cà Phê");
        setPreferredSize(new java.awt.Dimension(32767, 32767));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        panelNavBar.setBackground(new java.awt.Color(204, 255, 204));
        panelNavBar.setPreferredSize(new java.awt.Dimension(400, 2489));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DANH MỤC QUẢN LÝ");

        lblAdminName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblAdminName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        lblAdminName.setText("Xin chào!");

        panelNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelNhanVien.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/team.png"))); // NOI18N
        jLabel2.setText("     Quản lý Nhân Viên");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelNhanVienLayout = new javax.swing.GroupLayout(panelNhanVien);
        panelNhanVien.setLayout(panelNhanVienLayout);
        panelNhanVienLayout.setHorizontalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        panelNhanVienLayout.setVerticalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelKhachHang.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer.png"))); // NOI18N
        jLabel3.setText("     Quản lý Khách hàng");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        panelThucDon.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        jLabel4.setText("     Quản lý Thực đơn");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelThucDonLayout = new javax.swing.GroupLayout(panelThucDon);
        panelThucDon.setLayout(panelThucDonLayout);
        panelThucDonLayout.setHorizontalGroup(
            panelThucDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThucDonLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelThucDonLayout.setVerticalGroup(
            panelThucDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThucDonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        panelHoaDon.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice.png"))); // NOI18N
        jLabel7.setText("     Quản lý Hóa đơn");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelHoaDonLayout = new javax.swing.GroupLayout(panelHoaDon);
        panelHoaDon.setLayout(panelHoaDonLayout);
        panelHoaDonLayout.setHorizontalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoaDonLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelHoaDonLayout.setVerticalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoaDonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        panelReport.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report.png"))); // NOI18N
        jLabel5.setText("     Tạo báo cáo");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReportLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        panelPhieuXuat2.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout panelPhieuXuat2Layout = new javax.swing.GroupLayout(panelPhieuXuat2);
        panelPhieuXuat2.setLayout(panelPhieuXuat2Layout);
        panelPhieuXuat2Layout.setHorizontalGroup(
            panelPhieuXuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPhieuXuat2Layout.setVerticalGroup(
            panelPhieuXuat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        panelPhieuXuat1.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout panelPhieuXuat1Layout = new javax.swing.GroupLayout(panelPhieuXuat1);
        panelPhieuXuat1.setLayout(panelPhieuXuat1Layout);
        panelPhieuXuat1Layout.setHorizontalGroup(
            panelPhieuXuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPhieuXuat1Layout.setVerticalGroup(
            panelPhieuXuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        panelPhieuXuat.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout panelPhieuXuatLayout = new javax.swing.GroupLayout(panelPhieuXuat);
        panelPhieuXuat.setLayout(panelPhieuXuatLayout);
        panelPhieuXuatLayout.setHorizontalGroup(
            panelPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPhieuXuatLayout.setVerticalGroup(
            panelPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        panelDangXuat.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabel6.setText("     Đăng xuất");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 40, 25, 10));

        javax.swing.GroupLayout panelDangXuatLayout = new javax.swing.GroupLayout(panelDangXuat);
        panelDangXuat.setLayout(panelDangXuatLayout);
        panelDangXuatLayout.setHorizontalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDangXuatLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelDangXuatLayout.setVerticalGroup(
            panelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDangXuatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        javax.swing.GroupLayout panelNavBarLayout = new javax.swing.GroupLayout(panelNavBar);
        panelNavBar.setLayout(panelNavBarLayout);
        panelNavBarLayout.setHorizontalGroup(
            panelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavBarLayout.createSequentialGroup()
                .addGroup(panelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdminName))
                    .addComponent(panelThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNavBarLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addComponent(panelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPhieuXuat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPhieuXuat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
        );
        panelNavBarLayout.setVerticalGroup(
            panelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavBarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblAdminName)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(panelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panelReport, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPhieuXuat1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPhieuXuat2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1276, Short.MAX_VALUE))
        );

        getContentPane().add(panelNavBar);

        panelMainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMainContentLayout = new javax.swing.GroupLayout(panelMainContent);
        panelMainContent.setLayout(panelMainContentLayout);
        panelMainContentLayout.setHorizontalGroup(
            panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
        );
        panelMainContentLayout.setVerticalGroup(
            panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2489, Short.MAX_VALUE)
        );

        getContentPane().add(panelMainContent);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JPanel panelDangXuat;
    private javax.swing.JPanel panelHoaDon;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JPanel panelMainContent;
    private javax.swing.JPanel panelNavBar;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelPhieuXuat;
    private javax.swing.JPanel panelPhieuXuat1;
    private javax.swing.JPanel panelPhieuXuat2;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelThucDon;
    // End of variables declaration//GEN-END:variables
}
