/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Models.Product;
import Repositories.ProductRepository;
import java.awt.Desktop;
import java.awt.Frame;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author ThanhNhan
 */
public class Form_Product extends javax.swing.JPanel implements Form_Product_AddItem.DataChangedListener, Form_Product_UpdateItem.DataChangedListener{

    private ProductRepository productRepo = new ProductRepository();
    /**
     * Creates new form Form_Product
     */
    public Form_Product() {
        initComponents();
        loadProductToTable();
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setBorder(BorderFactory.createEmptyBorder(6, 6, 6, 6)); 

        for (int i = 0; i < tableProducts.getColumnCount(); i++) {
            tableProducts.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    public void onDataChanged() {
        loadProductToTable();
    }
    
    private java.sql.Date convertStringToDate(String dateString) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd"); 
        try {
            java.util.Date parsed = format.parse(dateString);
            return new java.sql.Date(parsed.getTime()); 
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ. Vui lòng nhập theo yyyy-MM-dd.");
            return null;
        }
    }
    
    public void loadProductToTable() {
        DefaultTableModel model = (DefaultTableModel) tableProducts.getModel();
        model.setRowCount(0);
        
        List<Product> products = productRepo.getAllProducts();

        for (Product p : products) {
            model.addRow(new Object[]{
                p.getProductID(), 
                p.getProductName(),
                p.getProductQuantity(),
                p.getProductPrice(),
                p.getProductImage()
            });
        }
    }
    
    private void openFile(String filePath) {
        try {
            File file = new File(filePath);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(file);
            } else {
                JOptionPane.showMessageDialog(this, "Không thể mở file.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi mở file: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFunction = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnExcel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelFunction.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        panelFunction.setLayout(new javax.swing.BoxLayout(panelFunction, javax.swing.BoxLayout.X_AXIS));

        jToolBar1.setRollover(true);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnInfo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info.png"))); // NOI18N
        btnInfo.setText("Chi tiết");
        btnInfo.setFocusable(false);
        btnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfo.setMargin(new java.awt.Insets(5, 20, 5, 20));
        btnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInfo);

        panelFunction.add(jToolBar1);

        jToolBar2.setRollover(true);

        btnExcel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sheets.png"))); // NOI18N
        btnExcel.setText("Xuất file Excel");
        btnExcel.setFocusable(false);
        btnExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        jToolBar2.add(btnExcel);

        panelFunction.add(jToolBar2);

        add(panelFunction);

        tableProducts.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Hình ảnh"
            }
        ));
        jScrollPane2.setViewportView(tableProducts);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Form_Product_AddItem dialog = new Form_Product_AddItem((Frame)SwingUtilities.getWindowAncestor(this), true);
        dialog.setLocationRelativeTo(this);
        dialog.setDataChangedListener(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableProducts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một món ăn trong thực đơn để xóa.");
            return;
        }

        String productIDToDelete = (String) tableProducts.getValueAt(selectedRow, 0);

        int confirmResult = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn xóa món ăn có mã món ăn: " + productIDToDelete.trim() + "?",
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION);

        if (confirmResult == JOptionPane.YES_OPTION) {
            if (productRepo.deleteProduct(productIDToDelete)) {
                JOptionPane.showMessageDialog(this, "Xóa món ăn khỏi thực đơn thành công!");
                loadProductToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa món ăn khỏi thực đơn thất bại.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableProducts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một món ăn trong thực đơn để sửa.");
            return;
        }

        String productID = (String) tableProducts.getValueAt(selectedRow, 0);
        String productName = (String) tableProducts.getValueAt(selectedRow, 1);
        int productQuantity = (int) tableProducts.getValueAt(selectedRow, 2);
        int productPrice = (int) tableProducts.getValueAt(selectedRow, 3);
        String productImage = (String) tableProducts.getValueAt(selectedRow, 4);

        Form_Product_UpdateItem updateItemDialog = new Form_Product_UpdateItem((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        updateItemDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        updateItemDialog.setLocationRelativeTo(this);
        updateItemDialog.setModal(true);

        // Điền dữ liệu vào các text field trên dialog
        updateItemDialog.setProductID(productID);
        updateItemDialog.setProductName(productName);
        updateItemDialog.setProductQuantity(productQuantity);
        updateItemDialog.setProductPrice(productPrice);
        updateItemDialog.setProductImage(productImage);

        // Hiển thị dialog cập nhật
        updateItemDialog.setDataChangedListener(this);
        updateItemDialog.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableProducts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một món ăn trong thực đơn để xem chi tiết.");
            return;
        }

        String productID = (String) tableProducts.getValueAt(selectedRow, 0);
        String productName = (String) tableProducts.getValueAt(selectedRow, 1);
        int productQuantity = (int) tableProducts.getValueAt(selectedRow, 2);
        int productPrice = (int) tableProducts.getValueAt(selectedRow, 3);
        String productImage = (String) tableProducts.getValueAt(selectedRow, 4);

        Form_Product_DetailInfo detailInfoDialog = new Form_Product_DetailInfo((java.awt.Frame) SwingUtilities.getWindowAncestor(this), true);
        detailInfoDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        detailInfoDialog.setLocationRelativeTo(this);

        detailInfoDialog.setProductID(productID);
        detailInfoDialog.setProductName(productName);
        detailInfoDialog.setProductQuantity(productQuantity);
        detailInfoDialog.setProductPrice(productPrice);
        detailInfoDialog.setProductImage(productImage);

        // Hiển thị dialog
        detailInfoDialog.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Chọn nơi lưu file Excel");

            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File saveFile = fileChooser.getSelectedFile();

                if (!saveFile.getName().toLowerCase().endsWith(".xlsx")) {
                    saveFile = new File(saveFile.toString() + ".xlsx");
                }

                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("ThucDon");

                Row headerRow = sheet.createRow(0);
                int columnCount = tableProducts.getColumnCount();

                for (int i = 0; i < columnCount; i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(tableProducts.getColumnName(i));
                }

                int rowCount = tableProducts.getRowCount();
                for (int j = 0; j < rowCount; j++) {
                    Row row = sheet.createRow(j + 1);

                    for (int k = 0; k < columnCount; k++) {
                        Cell cell = row.createCell(k);
                        Object value = tableProducts.getValueAt(j, k);

                        if (value != null) {
                            if (value instanceof Number) {
                                if (value instanceof Integer || value instanceof Long || value instanceof Double || value instanceof Float) {
                                    cell.setCellValue(((Number) value).doubleValue());
                                } else {
                                    cell.setCellValue(value.toString());
                                }
                            } else if (value instanceof java.util.Date) {
                                cell.setCellValue((java.util.Date) value);
                                CellStyle dateCellStyle = workbook.createCellStyle();
                                CreationHelper createHelper = workbook.getCreationHelper();
                                dateCellStyle.setDataFormat(createHelper.createDataFormat().getFormat("yyyy-MM-dd")); // Định dạng tùy chỉnh
                                cell.setCellStyle(dateCellStyle);

                            } else {
                                cell.setCellValue(value.toString());
                            }
                        }
                    }
                }

                try (FileOutputStream fileOut = new FileOutputStream(saveFile)) {
                    workbook.write(fileOut);
                }
                workbook.close();

                JOptionPane.showMessageDialog(this, "Xuất file Excel thành công!\nĐường dẫn: " + saveFile.getAbsolutePath(), "Thành công", JOptionPane.INFORMATION_MESSAGE);
                openFile(saveFile.getAbsolutePath());

            } else if (userSelection == JFileChooser.CANCEL_OPTION) {
                JOptionPane.showMessageDialog(this, "Hủy bỏ xuất file Excel.", "Hủy bỏ", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xuất file Excel: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnInfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JTable tableProducts;
    // End of variables declaration//GEN-END:variables
}
